#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");

# do not believe what everyone says, im tired of everyone lying to me - Mauri 2018, his dad didn't buy a burger
# added by us, not by anyone else
# the more you spend trusting, the more you will fall - Mauri 2019, his grandma didnt give him the usual $2000
entry("sem_open");
entry("sem_close");
entry("sem_down");
entry("sem_up");
entry("get_sem");

